import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, Check, ExternalLink, LoaderCircle, Mail, PackageCheck, Search, Truck } from "lucide-react";
import { useLanguage } from "../../i18n/LanguageContext.jsx";

const COPY = {
  es: { eyebrow:"LOGÍSTICA // SEGUIMIENTO", title:"Rastrea tu", accent:"pedido.", intro:"Consulta el estado registrado en WooCommerce y abre la guía de la transportadora cuando esté disponible.", order:"Número de pedido", email:"Correo usado en la compra", button:"Rastrear pedido", notFound:"No encontramos una orden que coincida con esos datos.", retry:"Revisa el número y el correo exactamente como aparecen en tu compra.", current:"Estado actual", number:"Número de guía", provider:"Transportadora", external:"Seguir con transportadora", updated:"Última actualización", stages:["Orden recibida","Preparando envío","En camino","Entregado"], cancelled:"Esta orden fue cancelada, falló o fue reembolsada." },
  en: { eyebrow:"LOGISTICS // TRACKING", title:"Track your", accent:"order.", intro:"Check the status recorded in WooCommerce and open the carrier page when available.", order:"Order number", email:"Email used at checkout", button:"Track order", notFound:"We could not find an order matching those details.", retry:"Check the number and email exactly as shown in your purchase.", current:"Current status", number:"Tracking number", provider:"Carrier", external:"Track with carrier", updated:"Last update", stages:["Order received","Preparing shipment","In transit","Delivered"], cancelled:"This order was cancelled, failed, or refunded." }
};

export default function OrderTracking(){
  const {language}=useLanguage(); const c=COPY[language]||COPY.es;
  const [form,setForm]=useState({order_number:"",email:""}); const [state,setState]=useState("idle"); const [order,setOrder]=useState(null);
  useEffect(()=>{ const number=new URLSearchParams(location.search).get("order")||""; setForm(v=>({...v,order_number:number})); fetch("/api/account/me",{credentials:"include"}).then(r=>r.ok?r.json():null).then(p=>{if(p?.user?.email)setForm(v=>({...v,email:p.user.email}))}).catch(()=>{}); },[]);
  const submit=async(e)=>{e.preventDefault();setState("loading");setOrder(null);try{const r=await fetch("/api/account/track-order",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const p=await r.json();if(!r.ok||!p.order)throw 0;setOrder(p.order);setState("ready")}catch{setState("error")}};
  const tracking=order?.tracking||{}; const stage=Number(tracking.stage??0); const date=v=>{try{return new Intl.DateTimeFormat(language==="es"?"es-CO":"en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}catch{return v||"—"}};
  return <main className="min-h-screen px-4 pb-24 pt-[var(--lab-mobile-page-top)] text-white sm:px-6 sm:pt-[12rem] lg:px-8"><div className="mx-auto max-w-[980px]">
    <a href="/" className="inline-flex items-center gap-2 font-mono text-[8px] uppercase tracking-[.16em] text-slate-500 hover:text-cyan-300"><ArrowLeft size={13}/>LAB_CORE</a>
    <div className="mt-8 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><section><p className="font-mono text-[9px] font-bold uppercase tracking-[.22em] text-cyan-300">{c.eyebrow}</p><h1 className="mt-4 font-['Orbitron'] text-4xl font-black uppercase leading-none tracking-[-.05em] sm:text-5xl">{c.title} <span className="text-cyan-300">{c.accent}</span></h1><p className="mt-5 text-sm leading-7 text-slate-400">{c.intro}</p></section>
    <section className="border border-cyan-300/15 bg-[#061021]/80 p-5 shadow-[0_30px_90px_rgba(0,0,0,.3)] sm:p-7"><form onSubmit={submit} className="grid gap-4">
      <label><span className="mb-2 block font-mono text-[8px] uppercase text-slate-500">{c.order}</span><div className="relative"><PackageCheck className="absolute left-4 top-1/2 -translate-y-1/2 text-cyan-300" size={15}/><input required value={form.order_number} onChange={e=>setForm({...form,order_number:e.target.value})} placeholder="#1234" className="h-14 w-full border border-white/10 bg-[#020617] pl-11 pr-4 font-mono text-xs outline-none focus:border-cyan-300/45"/></div></label>
      <label><span className="mb-2 block font-mono text-[8px] uppercase text-slate-500">{c.email}</span><div className="relative"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-cyan-300" size={15}/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="correo@ejemplo.com" className="h-14 w-full border border-white/10 bg-[#020617] pl-11 pr-4 font-mono text-xs outline-none focus:border-cyan-300/45"/></div></label>
      <button disabled={state==="loading"} className="flex min-h-13 items-center justify-center gap-2 bg-cyan-300 px-5 font-['Orbitron'] text-[9px] font-black uppercase tracking-[.13em] text-[#020617] hover:bg-white disabled:opacity-60">{state==="loading"?<LoaderCircle className="animate-spin" size={15}/>:<Search size={15}/>} {c.button}</button>
    </form>{state==="error"&&<div className="mt-5 flex gap-3 border border-red-300/15 bg-red-300/[.04] p-4"><AlertTriangle className="shrink-0 text-red-300" size={17}/><div><p className="font-mono text-[9px] text-red-200">{c.notFound}</p><p className="mt-2 font-mono text-[8px] text-red-100/50">{c.retry}</p></div></div>}</section></div>
    {order&&<section className="mt-8 border border-white/10 bg-[#040d1e] p-5 sm:p-8"><div className="flex flex-col gap-4 border-b border-white/10 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[8px] uppercase text-slate-600">ORDER // {order.number}</p><h2 className="mt-2 font-['Orbitron'] text-lg font-black uppercase">{c.current}: <span className="text-cyan-300">{order.status_label||order.status}</span></h2></div><p className="font-mono text-[8px] text-slate-500">{c.updated}: {date(tracking.updated_at)}</p></div>
      {stage<0?<div className="mt-6 flex gap-3 border border-red-300/15 p-4 text-red-200"><AlertTriangle size={17}/><p className="font-mono text-[9px]">{c.cancelled}</p></div>:<div className="mt-8 grid grid-cols-4">{c.stages.map((label,index)=>{const done=index<=stage;return <div key={label} className="relative text-center"><div className={`absolute left-0 right-0 top-4 h-px ${done?"bg-cyan-300/60":"bg-white/10"}`}/><span className={`relative mx-auto flex h-8 w-8 items-center justify-center rounded-full border ${done?"border-cyan-300 bg-cyan-300 text-[#020617]":"border-white/15 bg-[#040d1e] text-slate-600"}`}>{done?<Check size={14}/>:index+1}</span><p className={`mt-3 font-mono text-[7px] uppercase leading-4 sm:text-[8px] ${done?"text-white":"text-slate-600"}`}>{label}</p></div>})}</div>}
      <div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="border border-white/[.08] p-4"><p className="font-mono text-[7px] uppercase text-slate-600">{c.number}</p><p className="mt-2 font-mono text-sm font-bold">{tracking.number||"—"}</p></div><div className="border border-white/[.08] p-4"><p className="font-mono text-[7px] uppercase text-slate-600">{c.provider}</p><p className="mt-2 font-mono text-sm font-bold">{tracking.provider||"—"}</p></div></div>
      {tracking.url&&<a href={tracking.url} target="_blank" rel="noreferrer" className="mt-4 flex min-h-12 items-center justify-center gap-2 bg-cyan-300 px-5 font-['Orbitron'] text-[8px] font-black uppercase text-[#020617] hover:bg-white"><Truck size={15}/>{c.external}<ExternalLink size={13}/></a>}
    </section>}
  </div></main>;
}
